version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.sentry:sentry
    versions:
    - 4.1.0
    - 4.2.0
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.2
