plugin_version=1.5.0-SNAPSHOT

# External dep versions
paper_version=1.21-R0.1-SNAPSHOT
lombok_version=1.18.30
mongodb_driver_version=5.1.0
jetbrains_annotations=24.0.0
json_version=20240303

# Cloudnet version
cloudnet_version=4.0.0-RC10

# Internal dep versions
core_version=1.1.0-SNAPSHOT
canvas_version=1.8.0-SNAPSHOT
cloud_utils_version=1.2.1