name: Bingo
version: ${project.version}
main: de.nehlen.bingo.Bingo
api-version: 1.20
depend: [ SpooklyCloudnetUtils, Spookly-Core ]
authors: [ NEhlen ]
commands:
  bingo:
    aliases:
      - b
      - bi
      - items
      - i
  start:
    aliases:
      - s
  setspawn:
  backpack:
    aliases:
      - bp
  stats:
    aliases:
      - statistics
  hud:
  reroll: