main: de.spookly.bingo.Bingo
name: SpooklyBingo
version: '${version}'
api-version: 1.21
website: https://spookly.net
author:
  - Niklas Ehlen
depend:
  - SpooklyCloudnetUtils
  - SpooklyCore
libraries:
  - 'org.mongodb:mongodb-driver-reactivestreams:${mongodb_driver_version}'
  - 'org.json:json:${json_version}'
commands:
  bingo:
    aliases:
      - b
      - bi
      - items
      - i
  start:
    aliases:
      - s
  setspawn:
  backpack:
    aliases:
      - bp
  stats:
    aliases:
      - statistics
  hud:
  reroll: